//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this ile may cause incorrect behavior and will be lost i
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP_CororConvertinWithMatrixTransormation.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsot.VisualStudio.Editors.SettingsDesigner.SettingsSingleileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings deaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Deault
        {
            get
            {
                return deaultInstance;
            }
        }
    }
}
